# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a224d32aa2d65277c8b10f554e62f7bed295b05530c32c3dc5d8137eb0ff388083652d3e89c88835e0b8aa40e93ac5ef1d1ffa826363704da69687db4fc96456

test:
  secret_key_base: 90af269b81f90fa4069695aa1f2dc950d1ec42c16d19631f22f05a8168350db003fbda9fb0f517505f66df20c981d8951934180b67ae81ce781c4db3be0a24ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
